# This is a workflow for building the kasa_cli executable on all three major platforms.

name: Build-Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["DP100"]

  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.11"
          spec: "gui_source/build.spec"
          requirements: "gui_source/requirements.txt"
          upload_exe_with_name: "DP100GUI"
          compression_level: 9
          options: --upx-dir "./.upx"

  build-numba:
    runs-on: windows-latest
    steps:
      - name: Build Numba
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.11"
          spec: "gui_source/build_numba.spec"
          requirements: "gui_source/requirements.txt"
          upload_exe_with_name: "DP100GUI-Numba"
          compression_level: 9
          options: --upx-dir "./.upx"
